<?php

namespace Database\Seeders;

use App\Models\Anggota;
use Illuminate\Database\Seeder;

class AnggotaSeeder extends Seeder
{
    public function run(): void
    {
        $anggotas = [
            [
                'namaLengkap'       => 'Ahmad Fauzi',
                'tempatLahir'       => 'Jakarta',
                'tanggalLahir'      => '1985-03-15',
                'jenisKelamin'      => 'Laki-laki',
                'agama'             => 'Islam',
                'statusPerkawinan'  => 'Menikah',
                'kewarganegaraan'   => 'WNI',
                'nomorKTP'          => '3171051503850001',
                'nomorKK'           => '3171051503850000',
                'alamatKTP'         => 'Jl. Cempaka Putih Raya No. 12, RT 005/RW 003, Cempaka Putih Timur, Jakarta Pusat 10510',
                'alamatDomisili'    => null,
                'nomorHP'           => '081234567891',
                'email'             => 'ahmad.fauzi@email.com',
                'pekerjaan'         => 'Wiraswasta',
                'namaTempatKerja'   => 'Toko Bangunan Maju Jaya',
                'alamatTempatKerja' => 'Jl. Johar Baru No. 45, Jakarta Pusat',
                'jabatan'           => 'Pemilik',
                'penghasilan'       => 8000000,
                'simpananWajib'     => 200000,
                'nomorRekening'     => '1234567890',
                'statusAnggota'     => 'aktif',
            ],
            [
                'namaLengkap'       => 'Dewi Kusumawati',
                'tempatLahir'       => 'Bandung',
                'tanggalLahir'      => '1990-07-22',
                'jenisKelamin'      => 'Perempuan',
                'agama'             => 'Islam',
                'statusPerkawinan'  => 'Menikah',
                'kewarganegaraan'   => 'WNI',
                'nomorKTP'          => '3274046207900001',
                'nomorKK'           => '3274046207900000',
                'alamatKTP'         => 'Jl. Kemang Selatan No. 8, RT 002/RW 001, Kemang, Jakarta Selatan 12730',
                'alamatDomisili'    => 'Jl. Bangka Raya No. 20, Mampang Prapatan, Jakarta Selatan',
                'nomorHP'           => '082134567892',
                'email'             => 'dewi.kusuma@email.com',
                'pekerjaan'         => 'PNS',
                'namaTempatKerja'   => 'Dinas Pendidikan DKI Jakarta',
                'alamatTempatKerja' => 'Jl. Jenderal Gatot Subroto No. 40-41, Jakarta Selatan',
                'jabatan'           => 'Staf Administrasi',
                'penghasilan'       => 5500000,
                'simpananWajib'     => 150000,
                'nomorRekening'     => '0987654321',
                'statusAnggota'     => 'aktif',
            ],
            [
                'namaLengkap'       => 'Rudi Hartono',
                'tempatLahir'       => 'Surabaya',
                'tanggalLahir'      => '1978-11-08',
                'jenisKelamin'      => 'Laki-laki',
                'agama'             => 'Kristen Protestan',
                'statusPerkawinan'  => 'Menikah',
                'kewarganegaraan'   => 'WNI',
                'nomorKTP'          => '3578071108780002',
                'nomorKK'           => '3578071108780001',
                'alamatKTP'         => 'Jl. Kelapa Gading Boulevard No. 5, RT 003/RW 002, Kelapa Gading, Jakarta Utara 14240',
                'alamatDomisili'    => null,
                'nomorHP'           => '083234567893',
                'email'             => 'rudi.hartono@gmail.com',
                'pekerjaan'         => 'Karyawan Swasta',
                'namaTempatKerja'   => 'PT Maju Bersama Indonesia',
                'alamatTempatKerja' => 'Jl. TB Simatupang No. 100, Jakarta Selatan',
                'jabatan'           => 'Supervisor Logistik',
                'penghasilan'       => 7500000,
                'simpananWajib'     => 200000,
                'nomorRekening'     => '1122334455',
                'statusAnggota'     => 'aktif',
            ],
            [
                'namaLengkap'       => 'Sari Indah Lestari',
                'tempatLahir'       => 'Yogyakarta',
                'tanggalLahir'      => '1995-04-30',
                'jenisKelamin'      => 'Perempuan',
                'agama'             => 'Islam',
                'statusPerkawinan'  => 'Belum Menikah',
                'kewarganegaraan'   => 'WNI',
                'nomorKTP'          => '3404263004950001',
                'nomorKK'           => '3404263004950000',
                'alamatKTP'         => 'Jl. Palmerah Utara No. 17, RT 007/RW 004, Palmerah, Jakarta Barat 11480',
                'alamatDomisili'    => null,
                'nomorHP'           => '085234567894',
                'email'             => 'sari.lestari@email.com',
                'pekerjaan'         => 'Guru',
                'namaTempatKerja'   => 'SD Negeri Palmerah 01 Pagi',
                'alamatTempatKerja' => 'Jl. Palmerah Selatan No. 22, Jakarta Barat',
                'jabatan'           => 'Guru Kelas',
                'penghasilan'       => 4500000,
                'simpananWajib'     => 100000,
                'nomorRekening'     => '5544332211',
                'statusAnggota'     => 'aktif',
            ],
            [
                'namaLengkap'       => 'Bambang Sutrisno',
                'tempatLahir'       => 'Solo',
                'tanggalLahir'      => '1970-09-12',
                'jenisKelamin'      => 'Laki-laki',
                'agama'             => 'Islam',
                'statusPerkawinan'  => 'Menikah',
                'kewarganegaraan'   => 'WNI',
                'nomorKTP'          => '3372061209700001',
                'nomorKK'           => '3372061209700000',
                'alamatKTP'         => 'Jl. Condet Raya No. 88, RT 011/RW 006, Batu Ampar, Jakarta Timur 13520',
                'alamatDomisili'    => null,
                'nomorHP'           => '087834567895',
                'email'             => null,
                'pekerjaan'         => 'Pedagang',
                'namaTempatKerja'   => 'Pasar Induk Kramat Jati',
                'alamatTempatKerja' => 'Jl. Raya Bogor KM 17, Jakarta Timur',
                'jabatan'           => null,
                'penghasilan'       => 6000000,
                'simpananWajib'     => 150000,
                'nomorRekening'     => '6677889900',
                'statusAnggota'     => 'aktif',
            ],
            [
                'namaLengkap'       => 'Rina Marlina',
                'tempatLahir'       => 'Bekasi',
                'tanggalLahir'      => '1988-12-25',
                'jenisKelamin'      => 'Perempuan',
                'agama'             => 'Islam',
                'statusPerkawinan'  => 'Cerai Hidup',
                'kewarganegaraan'   => 'WNI',
                'nomorKTP'          => '3275062512880001',
                'nomorKK'           => '3275062512880000',
                'alamatKTP'         => 'Jl. Harapan Indah Blok B2 No. 14, RT 009/RW 005, Pejuang, Bekasi Barat 17131',
                'alamatDomisili'    => 'Jl. Tomang Raya No. 55, Tomang, Jakarta Barat',
                'nomorHP'           => '081334567896',
                'email'             => 'rina.marlina88@gmail.com',
                'pekerjaan'         => 'Wirausaha',
                'namaTempatKerja'   => 'Salon Kecantikan Rina',
                'alamatTempatKerja' => 'Jl. Tomang Raya No. 55, Jakarta Barat',
                'jabatan'           => 'Pemilik',
                'penghasilan'       => 5000000,
                'simpananWajib'     => 100000,
                'nomorRekening'     => null,
                'statusAnggota'     => 'aktif',
            ],
            [
                'namaLengkap'       => 'Hendra Gunawan',
                'tempatLahir'       => 'Medan',
                'tanggalLahir'      => '1982-06-18',
                'jenisKelamin'      => 'Laki-laki',
                'agama'             => 'Buddha',
                'statusPerkawinan'  => 'Menikah',
                'kewarganegaraan'   => 'WNI',
                'nomorKTP'          => '1271071806820001',
                'nomorKK'           => '1271071806820000',
                'alamatKTP'         => 'Jl. Mangga Dua Raya No. 33, RT 001/RW 002, Ancol, Jakarta Utara 14430',
                'alamatDomisili'    => null,
                'nomorHP'           => '082234567897',
                'email'             => 'hendra.gw@email.com',
                'pekerjaan'         => 'Karyawan Swasta',
                'namaTempatKerja'   => 'CV Elektronik Jaya',
                'alamatTempatKerja' => 'ITC Mangga Dua Lt. 3, Jakarta Utara',
                'jabatan'           => 'Kepala Toko',
                'penghasilan'       => 9000000,
                'simpananWajib'     => 250000,
                'nomorRekening'     => '9988776655',
                'statusAnggota'     => 'nonaktif',
            ],
            [
                'namaLengkap'       => 'Fitri Handayani',
                'tempatLahir'       => 'Semarang',
                'tanggalLahir'      => '1993-02-14',
                'jenisKelamin'      => 'Perempuan',
                'agama'             => 'Islam',
                'statusPerkawinan'  => 'Belum Menikah',
                'kewarganegaraan'   => 'WNI',
                'nomorKTP'          => '3374041402930001',
                'nomorKK'           => '3374041402930000',
                'alamatKTP'         => 'Jl. Cipinang Cempedak No. 9, RT 006/RW 003, Cipinang, Jakarta Timur 13340',
                'alamatDomisili'    => null,
                'nomorHP'           => '083734567898',
                'email'             => 'fitri.hday@gmail.com',
                'pekerjaan'         => 'Perawat',
                'namaTempatKerja'   => 'RS Islam Jakarta Timur',
                'alamatTempatKerja' => 'Jl. Raya Pondok Kopi, Jakarta Timur',
                'jabatan'           => 'Perawat Pelaksana',
                'penghasilan'       => 5000000,
                'simpananWajib'     => 100000,
                'nomorRekening'     => '4433221100',
                'statusAnggota'     => 'aktif',
            ],
            [
                'namaLengkap'       => 'Agus Pramono',
                'tempatLahir'       => 'Purwokerto',
                'tanggalLahir'      => '1975-08-17',
                'jenisKelamin'      => 'Laki-laki',
                'agama'             => 'Islam',
                'statusPerkawinan'  => 'Menikah',
                'kewarganegaraan'   => 'WNI',
                'nomorKTP'          => '3302011708750002',
                'nomorKK'           => '3302011708750001',
                'alamatKTP'         => 'Jl. Rawa Belong No. 4, RT 008/RW 004, Rawa Belong, Jakarta Barat 11480',
                'alamatDomisili'    => null,
                'nomorHP'           => '085634567899',
                'email'             => null,
                'pekerjaan'         => 'Sopir',
                'namaTempatKerja'   => null,
                'alamatTempatKerja' => null,
                'jabatan'           => null,
                'penghasilan'       => 3500000,
                'simpananWajib'     => 75000,
                'nomorRekening'     => null,
                'statusAnggota'     => 'pending',
            ],
            [
                'namaLengkap'       => 'Nurul Hidayah',
                'tempatLahir'       => 'Makassar',
                'tanggalLahir'      => '1997-10-05',
                'jenisKelamin'      => 'Perempuan',
                'agama'             => 'Islam',
                'statusPerkawinan'  => 'Belum Menikah',
                'kewarganegaraan'   => 'WNI',
                'nomorKTP'          => '7371050510970001',
                'nomorKK'           => '7371050510970000',
                'alamatKTP'         => 'Jl. Tebet Timur Dalam No. 21, RT 004/RW 002, Tebet, Jakarta Selatan 12820',
                'alamatDomisili'    => null,
                'nomorHP'           => '081534568900',
                'email'             => 'nurul.hidayah97@email.com',
                'pekerjaan'         => 'Mahasiswa',
                'namaTempatKerja'   => 'Universitas Indonesia',
                'alamatTempatKerja' => 'Kampus UI Depok, Jawa Barat',
                'jabatan'           => null,
                'penghasilan'       => null,
                'simpananWajib'     => 50000,
                'nomorRekening'     => '1357924680',
                'statusAnggota'     => 'pending',
            ],
            [
                'namaLengkap'       => 'Wahyu Santoso',
                'tempatLahir'       => 'Malang',
                'tanggalLahir'      => '1980-05-20',
                'jenisKelamin'      => 'Laki-laki',
                'agama'             => 'Islam',
                'statusPerkawinan'  => 'Menikah',
                'kewarganegaraan'   => 'WNI',
                'nomorKTP'          => '3573072005800001',
                'nomorKK'           => '3573072005800000',
                'alamatKTP'         => 'Jl. Kembangan Selatan No. 10, RT 012/RW 007, Kembangan, Jakarta Barat 11610',
                'alamatDomisili'    => null,
                'nomorHP'           => '081634568901',
                'email'             => 'wahyu.snt80@gmail.com',
                'pekerjaan'         => 'Teknisi',
                'namaTempatKerja'   => 'PT Telkom Indonesia (Persero) Tbk',
                'alamatTempatKerja' => 'Jl. Gatot Subroto No. 52, Jakarta Selatan',
                'jabatan'           => 'Teknisi Senior',
                'penghasilan'       => 8500000,
                'simpananWajib'     => 200000,
                'nomorRekening'     => '2468013579',
                'statusAnggota'     => 'nonaktif',
            ],
            [
                'namaLengkap'       => 'Sri Wahyuni',
                'tempatLahir'       => 'Klaten',
                'tanggalLahir'      => '1992-01-11',
                'jenisKelamin'      => 'Perempuan',
                'agama'             => 'Islam',
                'statusPerkawinan'  => 'Menikah',
                'kewarganegaraan'   => 'WNI',
                'nomorKTP'          => '3310131101920001',
                'nomorKK'           => '3310131101920000',
                'alamatKTP'         => 'Jl. Duren Sawit Raya No. 30, RT 015/RW 009, Duren Sawit, Jakarta Timur 13440',
                'alamatDomisili'    => null,
                'nomorHP'           => '082334568902',
                'email'             => 'sri.wahyuni92@email.com',
                'pekerjaan'         => 'Ibu Rumah Tangga',
                'namaTempatKerja'   => null,
                'alamatTempatKerja' => null,
                'jabatan'           => null,
                'penghasilan'       => null,
                'simpananWajib'     => 75000,
                'nomorRekening'     => '0246813579',
                'statusAnggota'     => 'pending',
            ],
        ];

        foreach ($anggotas as $anggota) {
            Anggota::create($anggota);
        }
    }
}
